sudo: required

language: bash

services:
  - docker

before_install:
    - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
    - docker-compose --version
    - docker-compose up -d

script:
    - docker-compose stop
