data:
  build: data/.
mysql:
  image: mysql
  ports:
  - "3306:3306"
  environment:
  - MYSQL_DATABASE=benchmark
  - MYSQL_ROOT_PASSWORD=password
  volumes:
  - ./data:/docker-entrypoint-initdb.d
  volumes_from:
  - data
 
 

  

