data:
  build: data/.
mysql:
  image: mysql
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=password
  volumes:
  - ./data:/docker-entrypoint-initdb.d
  volumes_from:
  - data
postgres:
  image: postgres
  ports:
  - "3307:3306"
  environment:
  - POSTGRES_PASSWORD = password
  - POSTGRES_DB = benchmark
mongo:
  image: mongo
  ports:
    -  "27019:27017"
couchdb:
  image: tutum/couchdb
  ports:
    - "5984:5984"
  environment:
  - COUCHDB_PASS= password
elasticserach:
  image: elasticsearch:1.4
  ports:
  - "9200:9200"
  - "9300:9300"
