bsbm_generator:
  build: bsbm_generator
  environment:
   - SCALING_FACTOR=250
   - db=bsbm
  volumes_from:
   - data
bsbmloader:
  build: bsbmloader
  environment:
    - db="bsbm"
  links:
    - mysql
    - mongodb
    - elasticsearch
    - postgres
    - couchdb
  volumes_from:
    - data
mysql:
  image: mysql
  ports:
   - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: benchmark
  volumes_from:
   - data
postgres:
  image: postgres
  ports:
   - "3308:3307"
  environment:
    POSTGRES_PASSWORD: password
    POSTGRES_DB: bsbm
  volumes_from:
   - data
mongodb:
  image: mongo
  ports:
    - "27018:27017"
  environment:
    - MONGO_DB= bsbm
  volumes_from:
   - data
couchdb:
  image: tutum/couchdb
  environment:
     COUCHDB_PASS: password
  ports:
   - "5984:5984"
  volumes_from:
   - data
elasticsearch:
  image: elasticsearch:1.4
  ports:
   - "9200:9200"
   - "9300:9300"
  volumes_from:
   - data
virtuoso:
  image: joernhees/virtuoso
  ports:
    - "8890:8890"
    - "1111:1111"
  volumes_from:
    - data
  environment:
   - "NumberOfBuffers=170000"
   - "MaxDirtyBuffers=130000"
data:
  image: java
  volumes:
   - ./scripts:/bsbm/scripts
   - /bsbm/data/benchmark/sql
   - /bsbm/data/benchmark/ttl
