bsbm_generator:
  build: bsbm_generator
  environment:
    - SCALING_FACTOR=1000

mysql:
  image: mysql
  volumes_from:
    - data
# docker-compose run mysql /bsbm/scripts/loadmysql.sh
# loadmysql contains instructions to load the sql data from /bsbm/data/source/bsbm/sql

    

mongodb:
  image: mongodb


data:
  image: java
  volumes:
    - /bsbm/data/source/bsbm/
    - /bsbm/data/dbs/monogo/
    - /bsbm/data/dbs/mysql/
    - /bsbm/data/dbs/virtuoso/
    - ./scripts:/bsbm/scripts/

 
 

  

