bsbm_generator:
  build: bsbm_generator
  environment:
   - SCALING_FACTOR=250
   - db=bsbm
  volumes_from:
   - data
teiid:
  image: teiid/teiid:8.10.0.Final
  volumes_from:
   - data
ontop:
  build: ontop_endpoint
  ports:
   - "3007:8080"
  volumes_from:
   - data
mysql:
  image: mysql
  ports:
   - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: benchmark
  volumes_from:
   - data
data:
  image: java
  volumes:
   - /bsbm/data/benchmark/sql
   - /bsbm/data/benchmark/ttl
   - ./scripts:/bsbm/scripts
