mysql1:
  extends:
    file: ../base/docker-compose.yml
    service: mysql
  volumes_from:
    - data
mysql2:
  extends:
    file: ../base/docker-compose.yml
    service: mysql2
  volumes_from:
    - data
bsbm:
  extends:
    file:  ../base/docker-compose.yml
    service: bsbm_generator
  volumes_from:
    - data
data:
  extends:
    file:  ../base/docker-compose.yml
    service: data
